version: '3.9'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: lara_nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7000:80"
    networks:
      - laravel

  db:
    image: postgres:14
    container_name: lara_db
    environment:
      POSTGRES_DB: lara_docker
      POSTGRES_PASSWORD: root
    ports:
      - "3457:3452"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    container_name: lara_php
    ports:
      - "9004:9004"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: lara_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - php
    networks:
      - laravel    
